import frappe
# from frappe.core.doctype.data_import.data_import import import_file
# # from frappe.utils.file_manager import save_file

# import frappe
# from frappe.modules.import_file import import_file_by_path
# from frappe.utils import get_bench_path
# import os
# from os.path import join

def after_migrate():
	fname = "parsimony_logo.svg"
	file_path = frappe.get_app_path("parsimony_wl", "public/images/{}".format(fname))
	print('file_path',file_path)
	with open(file_path, "rb") as f:
		file_content = f.read()

	logo_file = frappe.get_doc(
		{
			"doctype": "File",
			"file_name": fname,
			"content": file_content,
			"is_private": 0,
		}
	).insert()	
	# content =f"{PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjwhLS0gQ3JlYXRlZCB3aXRoIElua3NjYXBlIChodHRwOi8vd3d3Lmlua3NjYXBlLm9yZy8pIC0tPgoKPHN2ZwogICB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8iCiAgIHhtbG5zOmNjPSJodHRwOi8vY3JlYXRpdmVjb21tb25zLm9yZy9ucyMiCiAgIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyIKICAgeG1sbnM6c3ZnPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICAgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIgogICB4bWxuczpzb2RpcG9kaT0iaHR0cDovL3NvZGlwb2RpLnNvdXJjZWZvcmdlLm5ldC9EVEQvc29kaXBvZGktMC5kdGQiCiAgIHhtbG5zOmlua3NjYXBlPSJodHRwOi8vd3d3Lmlua3NjYXBlLm9yZy9uYW1lc3BhY2VzL2lua3NjYXBlIgogICB3aWR0aD0iMzAiCiAgIGhlaWdodD0iNDAiCiAgIHZpZXdCb3g9IjAgMCAzMCA0MCIKICAgaWQ9InN2ZzQ5NTQiCiAgIHZlcnNpb249IjEuMSIKICAgaW5rc2NhcGU6dmVyc2lvbj0iMC45MSByMTM3MjUiCiAgIHNvZGlwb2RpOmRvY25hbWU9InBhcnNpbW9ueWxvZ28uc3ZnIj4KICA8ZGVmcwogICAgIGlkPSJkZWZzNDk1NiIgLz4KICA8c29kaXBvZGk6bmFtZWR2aWV3CiAgICAgaWQ9ImJhc2UiCiAgICAgcGFnZWNvbG9yPSIjZmZmZmZmIgogICAgIGJvcmRlcmNvbG9yPSIjNjY2NjY2IgogICAgIGJvcmRlcm9wYWNpdHk9IjEuMCIKICAgICBpbmtzY2FwZTpwYWdlb3BhY2l0eT0iMC4wIgogICAgIGlua3NjYXBlOnBhZ2VzaGFkb3c9IjIiCiAgICAgaW5rc2NhcGU6em9vbT0iNy45MTM3MDM0IgogICAgIGlua3NjYXBlOmN4PSItMTAuNjg4OTE0IgogICAgIGlua3NjYXBlOmN5PSI0NC4yNzMwNTYiCiAgICAgaW5rc2NhcGU6ZG9jdW1lbnQtdW5pdHM9InB4IgogICAgIGlua3NjYXBlOmN1cnJlbnQtbGF5ZXI9ImxheWVyMSIKICAgICBzaG93Z3JpZD0iZmFsc2UiCiAgICAgdW5pdHM9InB4IgogICAgIGlua3NjYXBlOnNuYXAtcGFnZT0idHJ1ZSIKICAgICBpbmtzY2FwZTp3aW5kb3ctd2lkdGg9IjE4NTUiCiAgICAgaW5rc2NhcGU6d2luZG93LWhlaWdodD0iMTA1NiIKICAgICBpbmtzY2FwZTp3aW5kb3cteD0iNjUiCiAgICAgaW5rc2NhcGU6d2luZG93LXk9IjI0IgogICAgIGlua3NjYXBlOndpbmRvdy1tYXhpbWl6ZWQ9IjEiIC8+CiAgPG1ldGFkYXRhCiAgICAgaWQ9Im1ldGFkYXRhNDk1OSI+CiAgICA8cmRmOlJERj4KICAgICAgPGNjOldvcmsKICAgICAgICAgcmRmOmFib3V0PSIiPgogICAgICAgIDxkYzpmb3JtYXQ+aW1hZ2Uvc3ZnK3htbDwvZGM6Zm9ybWF0PgogICAgICAgIDxkYzp0eXBlCiAgICAgICAgICAgcmRmOnJlc291cmNlPSJodHRwOi8vcHVybC5vcmcvZGMvZGNtaXR5cGUvU3RpbGxJbWFnZSIgLz4KICAgICAgICA8ZGM6dGl0bGU+PC9kYzp0aXRsZT4KICAgICAgPC9jYzpXb3JrPgogICAgPC9yZGY6UkRGPgogIDwvbWV0YWRhdGE+CiAgPGcKICAgICBpbmtzY2FwZTpsYWJlbD0iTGF5ZXIgMSIKICAgICBpbmtzY2FwZTpncm91cG1vZGU9ImxheWVyIgogICAgIGlkPSJsYXllcjEiCiAgICAgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMCwtMTAxMi4zNjIxKSI+CiAgICA8ZwogICAgICAgaWQ9Imc1NjI0IgogICAgICAgdHJhbnNmb3JtPSJtYXRyaXgoMC4xMDA4ODg1MywwLDAsMC4xMDA4ODg1MywtMTcuMDI0Mzk2LDk4Ni43NDE3NykiPgogICAgICA8cGF0aAogICAgICAgICBzb2RpcG9kaTpub2RldHlwZXM9ImNjY2NjY2NjY2MiCiAgICAgICAgIGlua3NjYXBlOmNvbm5lY3Rvci1jdXJ2YXR1cmU9IjAiCiAgICAgICAgIGlkPSJwYXRoNTYwNSIKICAgICAgICAgZD0ibSAyMjQuNjQwMzUsMzg2LjIyMzA2IGMgLTQuNzEwMjMsMzAuOTU0MTYgNi4xMDk2MSw1Ny41ODAyNyAzNC4yNDM2OSw5MS4zNTI3MSAyMy42MjA4MiwzMi4xMzM3OCAxMy41NTUxLDc2LjU1NDc0IDU0Ljk4OTg4LDcyLjU4ODA1IDI1LjA2MTY3LC0xLjM3NCAzMS43MjIsLTI0LjY0MDg4IDMxLjcyMiwtNTEuMzYxMTggbCAxLjQ4MTIsLTEwNi44NzI3OCBjIDAuODAxOCwtNDYuMDMyNzMgLTgxLjc3ODYsLTM5LjY4NzM1IC00Ny44Nzk5OSwyNi40NTg4IGwgMjMuNzIwMSw0Ni4wMDM5MiBjIDAsMCA4Ljg5MTcsMjAuNjEyNzggMzMuMDM2NTEsMjAuNjEyNzggMzAuOTQwMTgsLTE0Ljk2MjIxIDU5Ljk2NTAyLC00Ny44MTg1NSA1NC42NDk3NSwtOTkuMTg0NyBDIDM5NS4zMTIxMSwyODIuNTI3ODEgMjQ1LjE2MywyNzUuMDk3NjIgMjI0LjY0MDM1LDM4Ni4yMjMwNiBaIgogICAgICAgICBzdHlsZT0iZmlsbDpub25lO2ZpbGwtb3BhY2l0eToxO2ZpbGwtcnVsZTpldmVub2RkO3N0cm9rZTojM2ZiMmJmO3N0cm9rZS13aWR0aDoyNDtzdHJva2UtbGluZWNhcDpidXR0O3N0cm9rZS1saW5lam9pbjptaXRlcjtzdHJva2UtbWl0ZXJsaW1pdDo0O3N0cm9rZS1kYXNoYXJyYXk6bm9uZTtzdHJva2Utb3BhY2l0eToxIiAvPgogICAgICA8ZWxsaXBzZQogICAgICAgICByeT0iMTYuMDY0ODQ2IgogICAgICAgICByeD0iODQuNDY3OTM0IgogICAgICAgICBjeT0iNTk0LjE3OTQ0IgogICAgICAgICBjeD0iMzEzLjM1NTEzIgogICAgICAgICBpZD0icGF0aDQyMDMtMyIKICAgICAgICAgc3R5bGU9ImZpbGw6I2ZiZGU3ZjtmaWxsLW9wYWNpdHk6MTtzdHJva2U6I2ZiZGU3ZjtzdHJva2Utd2lkdGg6MS4wNjQxMzA2NjtzdHJva2UtbWl0ZXJsaW1pdDo0O3N0cm9rZS1kYXNoYXJyYXk6bm9uZTtzdHJva2Utb3BhY2l0eToxIiAvPgogICAgPC9nPgogICAgPHJlY3QKICAgICAgIHN0eWxlPSJmaWxsOm5vbmU7ZmlsbC1ydWxlOmV2ZW5vZGQ7c3Ryb2tlOiMwMDAwMDA7c3Ryb2tlLXdpZHRoOjA7c3Ryb2tlLWxpbmVjYXA6YnV0dDtzdHJva2UtbGluZWpvaW46bWl0ZXI7c3Ryb2tlLW9wYWNpdHk6MTtzdHJva2UtbWl0ZXJsaW1pdDo0O3N0cm9rZS1kYXNoYXJyYXk6bm9uZSIKICAgICAgIGlkPSJyZWN0MzM3NSIKICAgICAgIHdpZHRoPSIzMCIKICAgICAgIGhlaWdodD0iMzkuOTk5OTYyIgogICAgICAgeD0iMCIKICAgICAgIHk9IjEwMTIuMzYyMSIgLz4KICA8L2c+Cjwvc3ZnPgo=}.svg"
	# dt = "File"
	# dn = "parsimony_logo.svg"
	# save_file(fname, content, dt, dn)

	# import_file(doctype='File', 
	#             file_path=frappe.utils.get_bench_path()+'/apps/parsimony_wl/parsimony_wl/public/files/ghg.txt', 
	#             file_type="SVG", 
	#             submit_after_import=False, 
	#             console=False)

	# if(not frappe.db.exists("Company-default_employee_petty_cash_payable_account_cf")):
# 		fname="parsimony_logo.svg"
# 		import_folder_path="{bench_path}/{app_folder_path}".format(bench_path=get_bench_path(),app_folder_path='/apps/parsimony_wl/parsimony_wl/public/parsimony_logo.svg')
# 		make_records(import_folder_path,fname)
	

# def make_records(path, fname):
# 	if os.path.isdir(path):
# 		import_file_by_path("{path}/{fname}".format(path=path, fname=fname))
	

   